### ISSUE TITLE
Doocumentation

### ISSUE THREAD

**Issue by ishanshah001** [CalvinWu4/RIT-Rate-My-Professors-Extension#1]
Is it possible for you to add documentation on how to add the extension?

**Comment by RJCrossgrove** [comment]
I found this through the rit reddit, if you are asking for yourself, the link is [https://www.reddit.com/r/rit/comments/jjpif0/i_made_an_extension_that_shows_the_rate_my/](url)
on this page, there is a link for both chrome and firefox. I can confirm that the chrome link will take you to the extension page for an easy installation.
Hope this helps

**Comment by CalvinWu4** [comment]
Added a link to the Chrome Extension on the readme
Thanks for the reminder
