### ISSUE TITLE
RateMyProfessors now seems to use a graphql API

### ISSUE THREAD

**Issue by MoralCode** [CalvinWu4/RIT-Rate-My-Professors-Extension#2]
![Screenshot_20230620_164635](https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension/assets/17362949/45230994-6954-4314-b3e9-f87a8c701af4)
![Screenshot_20230620_164856](https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension/assets/17362949/d59f8ca4-65ec-4845-8de0-277ee9d5600b)

Seems like the extension currently is trying to use an old, now-deprecated REST API

this seems to be a sample of a new endpoint that might be a replacement for the one currently in use:

```
curl 'https://www.ratemyprofessors.com/graphql' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: https://www.ratemyprofessors.com/professor/568275' -H 'Content-Type: application/json' -H 'Authorization: Basic dGVzdDp0ZXN0' -H 'Origin: https://www.ratemyprofessors.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: ccpa-notice-viewed-02=true; cid=-VEdhkoW5x-20230620; userSchoolId=U2Nob29sLTgwNw==; userSchoolLegacyId=807; userSchoolName=Rochester%20Institute%20of%20Technology' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-GPC: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '{"query":"query NewSearchTeachersQuery(\n  $query: TeacherSearchQuery!\n) {\n  newSearch {\n    teachers(query: $query) {\n      didFallback\n      edges {\n        cursor\n        node {\n          id\n          legacyId\n          firstName\n          lastName\n          school {\n            name\n            id\n          }\n          department\n        }\n      }\n    }\n  }\n}\n","variables":{"query":{"text":"aaron deever","schoolID":"U2Nob29sLTgwNw=="}}}'
```

**Comment by MoralCode** [comment]
their schema
![graphql-erd](https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension/assets/17362949/45c90111-3d5b-4244-aa6b-23c5683eda1c)

as obtained by putting the results of this query https://stackoverflow.com/a/46543255 into here : http://nathanrandal.com/graphql-visualizer/

**Comment by MoralCode** [comment]
Currently working on this in my fork on the graphql branch

Seems like the generated html is pretty tightly integrated with the responses from the API so its gonna be tricky/time consuming to swap the API out without breaking a ton of things


Having some instructions for how this was built and run might also help, currently running into an issue where `importScript` is not found

**Comment by CalvinWu4** [comment]
Wow thanks so much!

**Comment by MoralCode** [comment]
Currently working on this in my fork on the graphql branch

Seems like the generated html is pretty tightly integrated with the responses from the API so its gonna be tricky/time consuming to swap the API out without breaking a ton of things


Having some instructions for how this was built and run might also help, currently running into an issue where `importScript` is not foundn

**Comment by MoralCode** [comment]
weather update: it now kind of works

i pretty much just started over and bypassed a lot of the recursive name-trying logic cuz it looked complicated - so maybe thats why some of the names arent showing up

![Screenshot_20230621_194422](https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension/assets/17362949/6a51410a-8b0a-4485-945d-e6eb7f66c82b)
![Screenshot_20230621_194416](https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension/assets/17362949/a0d76ae4-069e-4672-b2d2-3765964d01c6)

**Comment by MoralCode** [comment]
jk it wasn't working because it was crashing.


![Screenshot_20230621_195151](https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension/assets/17362949/bf978bfd-9429-4126-9690-9c5ea9928bcf)

hover tooltips are uuh a lil broken tho

**Comment by MoralCode** [comment]
I suspect something in the tooltip library got updated and broke things.

Might try either downgrading tippy, messing with it until it works, or moving all the dom manipulation code into a html template to better see what the structure of that tooltip looks like


Guess this means I'm now live-tweeting updates on the nerdiest of Twitter alternatives haha

**Comment by MoralCode** [comment]
![Screenshot_20230622_114912](https://github.com/CalvinWu4/RIT-Rate-My-Professors-Extension/assets/17362949/6b0a1762-4b29-4edf-88ae-c778d4dd793e)

just a small CSS import/linking issue - of course
